---
azs:
- name: z1

networks:
- name: topgun
  subnets:
  - az: z1
    range: 10.234.0.0/16
    gateway: 10.234.0.1

- name: testflight
  subnets:
  - az: z1
    gateway: 10.244.15.1
    range: 10.244.15.0/30
    static:
    - 10.244.15.2
  - az: z1
    gateway: 10.244.16.1
    range: 10.244.16.0/24

vm_types:
- name: topgun
  network: topgun
- name: testflight
  network: testflight

compilation:
  az: z1
  workers: 3
  network: topgun
